version: '3.8'

networks:
  monitor-net:
    driver: bridge

services:
  # Serviço da aplicação Node.js/Express
  node-app:
    build: ./app
    container_name: node-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - monitor-net

  # Serviço do Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitor-net

  # Serviço do Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitor-net
